// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
  
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQRZlONlu5K3tN0ct2CimvBt8RLnoarU',
    appId: '1:858876634479:android:e3204ea243aa82a9b0749a',
    messagingSenderId: '858876634479',
    projectId: 'talkifyapp-2622d',
    storageBucket: 'talkifyapp-2622d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQ2R7I7QWMw0JOkBqivXj-r4KqI02abc',
    appId: '1:858876634479:ios:61888ebc6e9b8fb2b0749a',
    messagingSenderId: '858876634479',
    projectId: 'talkifyapp-2622d',
    storageBucket: 'talkifyapp-2622d.appspot.com',
    iosBundleId: 'com.example.talkifyApp',
  );

}